[project]
name = "start-python"
version = "0.1.0"
description = "Проєкт для вивчення програмування"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-awesome-pages-plugin>=2.10.1",
    "mkdocs-material>=9.6.15",
    "termynal>=0.13.0",
]
